on:
  workflow_call:
    inputs:
      project-key:
        required: true
        type: string
    secrets:
      SONARCLOUD_TOKEN:
        required: true

jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
